apiVersion: v1
data:
  server_port: VEJE
  db_password: VEJE
  db_username: VEJE
  db_host: VEJE
  db_port: VEJE
  db_sgm: VEJE
kind: Secret
metadata:
  name: backend
  namespace: search
type: Opaque
