apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: search
  labels:
    customer: search
    environment: development
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: thitiwas007007/search_test
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
          - name: SECRET_SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: backend
                key: server_port
          - name: SECRET_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend
                key: db_password
          - name: SECRET_DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend
                key: db_host
          - name: SECRET_DB_PORT
            valueFrom:
              secretKeyRef:
                name: backend
                key: db_port
          - name: SECRET_DB_SGM
            valueFrom:
              secretKeyRef:
                name: backend
                key: db_sgm
          - name: SECRET_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: backend
                key: db_username
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: search
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: search
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - targetPort: 8080 # port in pod
      port: 8080 # port in service
      nodePort: 30008 # external port
  selector:
    app: backend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: search
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
